// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VendorImport.Service.Data;

namespace VendorImport.Service.data.Migrations
{
    [DbContext(typeof(VendorDbContext))]
    [Migration("20190703183132_ReservationIdChange")]
    partial class ReservationIdChange
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("VendorImport.Service.Models.AdjustmentModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("CommissionAdjustment")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Confirmation")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<DateTime>("CreationDate");

                    b.Property<string>("GuestFirstName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("GuestLastName")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("Notes");

                    b.Property<string>("Property")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<int>("UploadCounter");

                    b.HasKey("Id");

                    b.HasIndex("Confirmation");

                    b.ToTable("Adjustments");
                });

            modelBuilder.Entity("VendorImport.Service.Models.InventoryReservationModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("ARNCallCenterFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("AffiliateName")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<DateTime>("BookedDate");

                    b.Property<decimal>("BookedRoomRevenue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CID");

                    b.Property<DateTime>("CheckoutDate");

                    b.Property<decimal>("CollectionExpense")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ComissionProcessingFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CommissionReceived")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Confirmation")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<DateTime>("CreationDate");

                    b.Property<decimal>("FlatAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("GuestFirstName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("GuestLastName")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<decimal>("NetCommission")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NetCommissionAfterSubAffiliate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Property")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<string>("RegistrationId")
                        .HasMaxLength(1000);

                    b.Property<string>("RegistrationName")
                        .HasMaxLength(1000);

                    b.Property<string>("ReservationId");

                    b.Property<string>("ReservationStatus")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("RoomNights");

                    b.Property<decimal>("RoomRevenue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<int>("SiteId");

                    b.Property<string>("SiteName")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<decimal>("SubAffiliateCommission")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UploadCounter");

                    b.HasKey("Id");

                    b.HasIndex("Confirmation", "SiteId");

                    b.ToTable("InventoryReservations");
                });

            modelBuilder.Entity("VendorImport.Service.Models.MerchantInventoryReservationModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("ARNCallCenterFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ARNTransactionFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("AffiliateName")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<decimal>("AffiliteCommissionPercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("BookedDate");

                    b.Property<string>("CID");

                    b.Property<decimal>("CardProcessingFees")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CheckoutDate");

                    b.Property<string>("Confirmation")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<decimal>("CostOfHotelWithTax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreationDate");

                    b.Property<decimal>("FlatAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GrossSaleWithTax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("GuestFirstName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("GuestLastName")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<decimal>("NetCommission")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NetCommissionAfterSubAffiliate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NetProfit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Property")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<string>("RegistrationId")
                        .HasMaxLength(1000);

                    b.Property<string>("RegistrationName")
                        .HasMaxLength(1000);

                    b.Property<string>("ReservationId");

                    b.Property<string>("ReservationStatus")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("RoomNights");

                    b.Property<decimal>("RoomRevenue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<int>("SiteId");

                    b.Property<string>("SiteName")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<decimal>("SubAffiliateCommission")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UploadCounter");

                    b.HasKey("Id");

                    b.HasIndex("Confirmation", "SiteId");

                    b.ToTable("MerchantInventoryReservations");
                });
#pragma warning restore 612, 618
        }
    }
}
